import smtplib
import time
from msvcrt import getch
import webbrowser
url ="https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4OCJCscgGps9PE251DtQQoLU5KOruuMs_p7_FS3ivlOc5AqREqHKbxaWynsnM2OGBAOmT98Ad0iEHyXsR_kVR8x-q0e8A"
print("Mail gonderme servisine hosgeldiniz.Devam etmek icin bir tusa basiniz.\n")
getch()
print("Uygulamamiz uzerinden mail gondermek icin once izin vermeniz gerekiyor.\n")
print("Lutfen acilan pencereden kullanacaginiz mail adresi icin izin veriniz.\n")
time.sleep(5)
webbrowser.open_new(url)
print("İznimizi verdigimize gore baslayabiliriz...\n")
time.sleep(1)
print("Mail adresinizi ve sifrenizi giriniz.(gmail)")
kmail=input("Mail adresiniz:\t")
ksifre=input("Sifreniz:\t")
print("Giris yapiyorum...")
time.sleep(1)
print("Basarili bir sekilde giris yapildi.")
time.sleep(1)
print("Alicinin mail adresini giriniz.\n")
alici=input("Mail adresi:\t")
time.sleep(1)
print("Tesekkurler.Sımdi gondermek istediginiz mesaji giriniz...\n")
mesaj =input("Mesajiniz: ")
print("Mesajiniz alindi.Maili gondermek icin herhangi bir tusa basiniz.\n")
getch()
print("Mailiniz gonderiliyor...")
mail = smtplib.SMTP("smtp.gmail.com",587)
mail.ehlo()
mail.starttls()
mail.login(kmail,ksifre)
mail.sendmail(kmail,alici,mesaj)
time.sleep(2)
print("Mailiniz basarili bir sekilde gonderildi.Cikis yapmak icin bir tusa basiniz.\n")
getch()
input()